name: Build & Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # macOS ARM (Apple Silicon)
          - os: macos-latest
            platform: darwin
            arch: arm64
            python-version: '3.11'
          # macOS Intel (x64)
          - os: macos-latest
            platform: darwin
            arch: x64
            python-version: '3.11'
          # Windows
          - os: windows-latest
            platform: win32
            arch: x64
            python-version: '3.11'
          # Linux (use 22.04 for broader glibc compatibility)
          - os: ubuntu-22.04
            platform: linux
            arch: x64
            python-version: '3.11'

    runs-on: ${{ matrix.os }}
    name: Build (${{ matrix.platform }}-${{ matrix.arch }})

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install pyinstaller

      - name: Bundle Python backend (Unix)
        if: runner.os != 'Windows'
        run: |
          chmod +x scripts/bundle-backend.sh
          bash scripts/bundle-backend.sh

      - name: Bundle Python backend (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          python -m PyInstaller `
            --name backend-sidecar `
            --onedir `
            --noconfirm `
            --clean `
            --hidden-import=uvicorn.logging `
            --hidden-import=uvicorn.loops `
            --hidden-import=uvicorn.loops.auto `
            --hidden-import=uvicorn.protocols `
            --hidden-import=uvicorn.protocols.http `
            --hidden-import=uvicorn.protocols.http.auto `
            --hidden-import=uvicorn.protocols.websockets `
            --hidden-import=uvicorn.protocols.websockets.auto `
            --hidden-import=uvicorn.lifespan `
            --hidden-import=uvicorn.lifespan.on `
            --hidden-import=uvicorn.lifespan.off `
            --hidden-import=backend.app `
            --hidden-import=backend.app.core `
            --hidden-import=backend.app.core.config `
            --hidden-import=backend.app.agent `
            --hidden-import=backend.app.agent.agent `
            --hidden-import=backend.app.agent.tools `
            --hidden-import=backend.app.services `
            --hidden-import=backend.app.services.dremio `
            --hidden-import=backend.app.services.facts `
            --hidden-import=backend.app.db `
            --hidden-import=backend.app.db.database `
            --hidden-import=backend.app.db.models `
            --hidden-import=backend.app.models.charts `
            --hidden-import=backend.app.models.history `
            --hidden-import=backend.app.routers.analytics `
            --hidden-import=multipart `
            --hidden-import=python_multipart `
            --hidden-import=pydantic_settings `
            --hidden-import=yaml `
            --hidden-import=dotenv `
            --hidden-import=langchain `
            --hidden-import=langchain_core `
            --hidden-import=langchain_core.tools `
            --hidden-import=langchain_core.messages `
            --hidden-import=langchain_openai `
            --hidden-import=langchain_anthropic `
            --hidden-import=langchain_google_genai `
            --hidden-import=langchain_mistralai `
            --hidden-import=langchain_groq `
            --hidden-import=langchain_aws `
            --hidden-import=langgraph `
            --hidden-import=langgraph.prebuilt `
            --hidden-import=langgraph.checkpoint.memory `
            --hidden-import=sqlalchemy.dialects.sqlite `
            --hidden-import=sqlalchemy.dialects.postgresql `
            --hidden-import=dremio_simple_query `
            --hidden-import=dremio_simple_query.connect `
            --hidden-import=dremio_simple_query.connectv2 `
            --hidden-import=duckdb `
            --hidden-import=polars `
            --hidden-import=tiktoken `
            --hidden-import=tiktoken_ext `
            --hidden-import=tiktoken_ext.openai_public `
            --hidden-import=httpx `
            --hidden-import=httpcore `
            --hidden-import=anyio `
            --hidden-import=anyio._backends `
            --hidden-import=anyio._backends._asyncio `
            --hidden-import=sniffio `
            --hidden-import=h11 `
            --hidden-import=orjson `
            --hidden-import=starlette `
            --hidden-import=starlette.routing `
            --hidden-import=starlette.middleware `
            --hidden-import=starlette.middleware.cors `
            --hidden-import=greenlet `
            --hidden-import=cryptography `
            --hidden-import=websockets `
            --collect-submodules=tiktoken `
            --collect-submodules=tiktoken_ext `
            --collect-submodules=starlette `
            --add-data "backend/dremio-docs;backend/dremio-docs" `
            --add-data "backend/app;backend/app" `
            backend/main.py
          Move-Item -Path dist/backend-sidecar -Destination backend-dist

      - name: Install npm dependencies
        run: npm ci

      - name: Install Linux packaging tools
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg fakeroot rpm

      - name: Build Electron installer
        run: npx electron-forge make --platform ${{ matrix.platform }} --arch ${{ matrix.arch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installer-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            out/make/**/*.dmg
            out/make/**/*.zip
            out/make/**/*.exe
            out/make/**/*.nupkg
            out/make/**/*.deb
            out/make/**/*.rpm
          if-no-files-found: warn

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/**/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
